name: Deploy 3D Model Server to Render

on:
  workflow_dispatch:

env:
  TARGET_IMAGE: 'ionutms/3d-model-server'
  TARGET_TAG: 'latest'
  RENDER_SERVICE_ID: 'srv-d0kqre7fte5s738u21mg'

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          echo "✅ Deploying $TARGET_IMAGE:$TARGET_TAG to Render..."
          curl -X POST "https://api.render.com/deploy/$RENDER_SERVICE_ID?key=${{ secrets.RENDER_DEPLOY_KEY }}"
          echo "Deployment triggered successfully!"