name: Deploy to Render on Docker Hub Push

on:
  workflow_dispatch:  # Manual trigger for testing
  registry_package:
    types: [published]
    
jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'ionutms/3d-model-server' && github.event.action == 'published' && github.event.target.tag == 'latest'
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-YOUR_SERVICE_ID?key=${{ secrets.RENDER_DEPLOY_KEY }}"